static_include: ['*.css', '*.js', '*.gif', '*.png', '*.ico']
static_exclude: []

emoji: ['🤣','😘','🤔','😜','😭','🧙','🏇','👓','🧦','👜',
'💍','🦍','🐶','🐺','🦊','🦁','🐻','🐣','🐥','🐳','🐬',
'🐠','🐌','🦋','🌻','🍎','🍉','🍣','🍜','🗾','🌏','🗼','⛩',
'🛵','🚋','⚓','☂','🎃','🏅','🏈','🎵']
